### ISSUE TITLE
DataObject in page/holder configuration

### ISSUE THREAD

**Issue by mi32dogs** [silverstripe/silverstripe-sharedraftcontent#54]
Hi Question,

I have a DataObject that is used in a page/holder configuration and has versioning, is there a way to make it work on those pages as well?

**Comment by tractorcow** [comment]
What happens if you try to use it? does it not show up?

I guess this is a bug that needs fixing then.

**Comment by mi32dogs** [comment]
On the pages it is there automatically, but how do I implement it on the Data Object?

**Comment by tractorcow** [comment]
Can you show me your code please? I'm not sure what is making it automatically appear.

**Comment by mi32dogs** [comment]
Ok, I think I used the wrong words.
I installed the module and run /dev/Build now if I edit a page I get the little share draft link in the bottom right of the page and this is great and works perfectly.

Now I have a Data Object with specials, so I created a Specials page type that extents page, in the page controller I created a public function getAllSpecials() what gets all the specials, in the template I loop through all the specials and display them. This works fine live and staged but in the share draft link it gets no specials.
If I try to debug it and put a break point in the getAllSpecials() functions it never gets there.

So 2 questions should it work or was it never intended to work like that?
Second, if it should work is there also a way to just get a preview link for one of the details pages?

code specials page

class SpecialsPage extends Page
{
	private static $has_many = array(
		'Specials' => 'Special',
	);
}

class SpecialsPage_Controller extends Page_Controller
{

	private static $allowed_actions = array(
		'details'
	);

	public function getAllSpecials()
	{
		$ThemeDir = $this->ThemeDir();
		Requirements::css($ThemeDir . '/css/Specials-styles.css');

		$specials = Specials::get()
			->where("List = 'true '")
			->where("(ListDate IS NULL OR ListDate = '') OR ListDate < NOW()")
			->sort('FirstDate');
		return $specials;
	}

	public function details(ss_HTTPRequest $request)
	{
		$special = Specials::get()->filter(array('UrlSegment' => $request->param('ID')))->first();

		if (!$special) {
			return $this->redirect('specials/');
		}
		return $special;
	}

}

**Comment by tractorcow** [comment]
Ok, some more questions:

- Does "Specials" have the Versioned extension?
- What does your SpecialsPage.ss template look like?
- What does the url for the preview look like?

I'm hoping that looking at the template will help me discover why the method is not being called.

It's possible that in the preview controller, methods in the page templates aren't always being routed back to the page controller properly.

**Comment by mi32dogs** [comment]
Yes, Specials has a Versioned extension i use the VersionedDataObject module

SpecialsPage.ss template:
<%--HEADER BLOCK --%>
<div class="container">
    <div class="row">
		<% include PageBanner %>
		<% include AddThisBar %>
    </div>
</div>
<div class="clearfix"></div>

<%-- CONTENT BLOCK --%>
<div class="container page-bg">
    <div class="row">

		<%--Add left sidebar--%>
		<% if $PageLayout = 'left' || $PageLayout = 'both' %>
            <div class="col-md-<% if $PageLayout = 'left' %>4<% else_if $PageLayout = 'both' %>3<% end_if %> left-page-sidebar">
                $leftsidebar
            </div>
		<% end_if %>
		
		<%--Add main Content--%>
        <div class="col-md-<% if $PageLayout = 'full' %>12<% else_if $PageLayout = 'left' || $PageLayout = 'right' %>8<% else_if $PageLayout = 'both' %>6<% end_if %> page-content">
            <div class="headline">$Title<% if $SubTitle %><br><small>$SubTitle</small><% end_if %></div>

			$Content

            <div class="well">
				<% if $AllSpecials %>
                    <table id="dataTable" class="table table-hover">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Special</th>
                        </tr>
                        </thead>
                        <tbody>

							<% loop $AllSpecials %>
                            <tr>
                                <td class="do-date">$Date.Format("M j, Y")</td>

                                <td class="do-wrap">
                                    <div class="do-img"><img src="$Image.URL"></div>
                                    <div class="do-HL">$Headline</div>
                                    <div class="do_txt">$Excerpt</div>
								</td>
                            </tr>
							<% end_loop %>
                        </tbody>
                    </table>
				<% else %>
                    <div class="do-wrapper">
                        <div class="do-HL">There are no specials at the moment</div>
                        <div class="clearfix"></div>
                    </div>
				<% end_if %>
            </div>

			$BottomContent
			$Form

        </div>

		<%--Add right sidebar--%>
		<% if $PageLayout = 'right' || $PageLayout = 'both' %>
            <div class="col-md-<% if $PageLayout = 'right' %>4<% else_if $PageLayout = 'both' %>3<% end_if %> page-sidebar">
				<% if $SideMenu = 1 %><% include SidebarMenu %><% end_if %>
				$SideContent
            </div>
		<% end_if %>

        <div class="clearall"></div>
    </div>
</div>
<div class="clearfix"></div>

-------------------------------------------------------------
the url for the preview look like:
http://sscain.local/preview/64c9646f158bce90/aa268e794a24b431
