### ISSUE TITLE
Call to a member function Link() on null

### ISSUE THREAD

**Issue by mandrew** [silverstripe/silverstripe-sharedraftcontent#56]
Fluent module seems to be breaking the share draft function :(

Message: Error: Call to a member function Link() on null
#0 Call to a member function Link() on null:: called at [/var/www/mysite/releases/35f6597cf2b1913f1d5f33846b0cf4f02bcc109f/fluent/code/extensions/FluentExtension.php:320]

see https://github.com/tractorcow/silverstripe-fluent/blob/master/code/extensions/FluentExtension.php#L353

**Comment by flashbackzoo** [comment]
@tractorcow that looks like an error in Fluent...

**Comment by tractorcow** [comment]
@mandrew can you please send me the URL of the page (normal view), and the actual share draft url too?

**Comment by tractorcow** [comment]
Oh, is that page published? Or is it on stage only when that breaks?

**Comment by tractorcow** [comment]
Not 100% sure what the issue is... it could be to do with stage not being opened correctly, or it could be due to fluent not respecting stage properly.

**Comment by mandrew** [comment]
@tractorcow it happens when someone clicks on the link and the page is stage only.

**Comment by mandrew** [comment]
We have a number of modules so I wouldn't be surprised if there is a conflict somewhere. One possible conflict could be with https://github.com/silverstripe/silverstripe-multi-domain/ which is also installed and has a global whitelist set, however we have - 'preview/*' set so I'm not sure if it is that?

**Comment by tractorcow** [comment]
I've raised an issue at Fluent for the time being https://github.com/tractorcow/silverstripe-fluent/issues/179

**Comment by robbieaverill** [comment]
Closing in favour of tractorcow/silverstripe-fluent#179
