### ISSUE TITLE
Preview link not working correctly with subsites

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-sharedraftcontent#63]
On a CWP site where subsites module is used together with this module, the preview link doesn't seem to use the correct primary domain of the respective subsite.

Based on that, an incorrect theme is used to preview the content.

**Comment by robbieaverill** [comment]
Thanks @michalkleiner - could you provide your CWP recipe and subsites version please?

**Comment by michalkleiner** [comment]
It was CWP recipe 1.5.2 and subsites 1.3.1. I'm trying to update to CWP 1.6.0 with latest subsites and will confirm if it's still happening.

**Comment by robbieaverill** [comment]
Yes, you're right. Reproduced on CWP 1.5

**Comment by robbieaverill** [comment]
Fix at #65

**Comment by wilr** [comment]
Merged and tagged `1.2.0`
