### ISSUE TITLE
Draft preview functionality not working in SS4

### ISSUE THREAD

**Issue by fspringveldt** [silverstripe/silverstripe-sharedraftcontent#66]
Currently in 2.x-dev the draft content preview is broken. 
1. MakeShareDraftLink doesn't work (first screenshot)
2. Fixing 1 above produces another issue (second screenshot) with Versioned namespace having changed
3. Then lastly the SS4 session updates weren't added to ShareDraftController->preview() (third screenshot)

PR to follow shortly.

![image](https://user-images.githubusercontent.com/10938392/31526068-18c9429e-b021-11e7-8fff-7736bd3d53fa.png)

![image](https://user-images.githubusercontent.com/10938392/31526114-522de760-b021-11e7-8843-8fffe1aa3cac.png)

![image](https://user-images.githubusercontent.com/10938392/31526176-a7765b30-b021-11e7-9172-d55cd50cb07a.png)

**Comment by robbieaverill** [comment]
Thanks
