### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-sharedraftcontent#71]
**User Story**

**Acceptance Criteria**

-

**Sub Tasks**

- [ ]
- [ ]
- [ ]

**Comment by robbieaverill** [comment]
Merged #73. @NightJar do you want to tag a beta release for this module now?

**Comment by NightJar** [comment]
Tagged 2.0.0-beta1 :)
