### ISSUE TITLE
Move Scrutinizer to silverstripe

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-sharedraftcontent#72]
Hey @dhensby, could you please move https://scrutinizer-ci.com/g/silverstripe-labs/silverstripe-sharedraftcontent/ to the SilverStripe organisation? Thanks!

**Comment by robbieaverill** [comment]
Bump @dhensby, whenever you get a chance =)

**Comment by dhensby** [comment]
weird, I don't have access to the settings page of that repo :/

I'll contact Scrutinizer to find out what's going on

**Comment by dhensby** [comment]
@assertchris you are the admin on this scrutinizer repo apparently - would you mind adding me as an admin, please? I can then associate it with the SS org and so on :)

**Comment by assertchris** [comment]
@dhensby there ya go!

**Comment by dhensby** [comment]
thanks @assertchris 

@robbieaverill all done https://scrutinizer-ci.com/g/silverstripe/silverstripe-sharedraftcontent/

**Comment by robbieaverill** [comment]
Thanks everyone!
