### ISSUE TITLE
Update of UI to match SS4

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-sharedraftcontent#78]
Use of an icon to indicate share would be the most obvious improvement but we should also consider the alignment of the "Share" text with the "Preview mode" toggle as they look out of place next to each other. Consider react popover.

Design ACs:
 * Swap position of share icon with page mode dropdown.
 * Add suitable icon to Share Draft button (text disappears on smaller viewports so the icon needs to be descriptive).
 * Add some descriptive text as to what the link does.
 * Add user guides to module.
 * Link to User guide for more information.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/563
- [x] https://github.com/silverstripe/silverstripe-admin/pull/564
- [x] https://github.com/silverstripe/silverstripe-admin/pull/565
- [ ] sharedraftcontent: #86

**Comment by sachajudd** [comment]
Details and design provided below:

- The UI should use a popover component
- Split mode—will be located between the Split mode icon and the Edit mode toggle.
- Edit mode—will be located on the far right of the publishing toolbar.
- New icons will need to be added to the CMS
- The 'Learn more' link will direct to a single page user guide (which I potentially will be adding)

Overview:
![share draft content](https://user-images.githubusercontent.com/24258161/41577111-24c85fb2-73df-11e8-8ec1-d36cc905f982.png)

![share draft content 2](https://user-images.githubusercontent.com/24258161/41577208-a52c8fb6-73df-11e8-9a5f-2121e37aca39.png)

Note:
- The Split mode example shows the button hover state.

**Comment by robbieaverill** [comment]
PR to add new fonts: https://github.com/silverstripe/silverstripe-admin/pull/563

**Comment by robbieaverill** [comment]
Double checking with @clarkepaul whether or not we should be updating the core popover designs as part of this issue. There seems to have been some efforts to do this already in SilverStripe 4.2.x to do this already (https://github.com/silverstripe/silverstripe-asset-admin/issues/779) but I'm not sure how successful it was.

Happy to make a new PR to update it further to match the designs in https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/components/5ae267cb98330300118a7851 if required, but for now will park it.

**Comment by clarkepaul** [comment]
@robbieaverill That would be great if you could do the final steps could be done to match the popover header to match the designs. Its a shame that weren't completed as part of the original issue, as they should have been. The styles that are wanting to apply should be applied to work generically and shouldn't break other instances of the popover. If anything comes up making it hard to complete the issue as per designs I'll create another issue to complete it.

FYI use the popover header class as per Bootstrap conventions.

**Comment by robbieaverill** [comment]
All PRs up in description

**Comment by robbieaverill** [comment]
Subtasked out the edit mode component into #87

**Comment by robbieaverill** [comment]
All merged
