### ISSUE TITLE
Decrease z-index to something sensible... if possible

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-sharedraftcontent#92]
https://github.com/silverstripe/silverstripe-sharedraftcontent/blob/ac3e4b41b9d36cc4a4cfb22df24ecdd76395f13d/client/src/styles/top-bar.scss#L20

I'm not sure why this is so high, but I've had a report from @lerni that it's causing him grief in relation with the `betternavigator` module.

~~This could be so high because of a competing CMS  element in the same stacking context, in which case there's not much to be done, except link this to another new issue on `silverstripe/admin`~~

**Comment by NightJar** [comment]
Oh, this is on the front-end, my mistake!
I can see the thought process behind this now...
since there's no control over 100% of the other elements on the front-end of the site, the z-index is so high so it will sit above everything else on the site.

Unfortunately in this case there is something we wish it to _not_ sit above on the site.
Altering CSS on the likes of `body` is dangerous and presumptuous, I don't think it's a good idea.

Maybe there's another way around this... 🤔

**Comment by robbieaverill** [comment]
People can easily adjust the frontend CSS to fix this in their projects, I don't think this is a big problem. Especially since, as you've said, this module needs to assume that it should be on top of everything else.

**Comment by lerni** [comment]
https://github.com/jonom/silverstripe-betternavigator proves, that the top-bar shouldn't be on top of everything. Otherwise you cannot collapse jonom/silverstripe-betternavigator, once it's open. I agree it can be fixed in projects css easily, but really easy would be, if you don’t have to.

**Comment by robbieaverill** [comment]
Fixed in #93, thanks @lerni
