### ISSUE TITLE
Clicking the 'Share Draft button' causes a 'Published page' to become 'Modified' in SS4.3

### ISSUE THREAD

**Issue by mithungc** [silverstripe/silverstripe-sharedraftcontent#96]
After creating a 'Share Draft link' for a page in the 'Published State' by clicking the 'Share Draft' button, refreshing the page shows that the status changes to 'Modified'.

**Comment by robbieaverill** [comment]
Reproduced with sharedraftcontent 2.2.x-dev. It doesn't show up immediately but when you refresh the page it does.

**Comment by robbieaverill** [comment]
Fix at https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/97

**Comment by NightJar** [comment]
Merged :)
