### ISSUE TITLE
[CWP 2.3] Browsing the CMS results in component not found errors 

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-sharedraftcontent#98]
**CWP 2.3.x-dev**

![image](https://user-images.githubusercontent.com/5170590/56939718-17171f80-6b5e-11e9-97e7-e355aeb5f676.png)

This is from browsing the CMS in a small viewport that doesn't allow split screen mode, and editing a user form page.

**Comment by ScopeyNZ** [comment]
This happens for me regardless of viewport size. It's using prop-types from `React` which has been removed. The "right" fix here is to upgrade the module to React 16.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/99
